fmoo/react-typeahead

dist/react-typeahead.js, src/typeahead/index.js, src/typeahead/option.js, src/typeahead/selector.js, test/bundle.js
I needed to have the event available in the callback and I think it makes sense to add this to the root repo. Also some lines actually indicate that this was the original intention.
I also added that the return value of the callback is return by all the wrappers, so you can also prevent the default action by returning false.
Use case: The default action of a click on <a href="#" /> breaks single page applications that rely on #-URLs.
=> Callback event

src/tokenizer/index.js
Small fix to pass down maxVisible prop when using Tokenizer.
Also added some missing semicolons.
=> pass down maxVisible prop from Tokenizer to Typeahead

dist/react-typeahead.js, package.json, src/tokenizer/index.js, src/tokenizer/token.js, src/typeahead/index.js, src/typeahead/option.js, src/typeahead/selector.js
React throws some warnings related to missing the `render` method and about calling components directly blah blah blah. Then it throws a warning about `classSet` deprecated before throwing a fatal error about object extensibility. [I've seen it before](https://github.com/jessy1092/react-semantify/issues/17) and the author of that module fixed it by factoring out `classSet` in favor of `classnames`. 
This PR replaces `React.addons.classSet` with [classnames](https://github.com/JedWatson/classnames), fixing the errors.
=> Fix rendering with React 0.13.x

dist/react-typeahead.js, package.json, src/tokenizer/index.js, src/tokenizer/token.js, src/typeahead/index.js, src/typeahead/option.js, src/typeahead/selector.js
This pull request removes window.React from the source files so they can be used for server side rendering with browserify & webpack.
Additionally I've updated the package.json to use `literalify` so the generated bundle keeps the original behavior.
The only thing it does not do is consider an external browserified bundle to provide React,
not sure if anybody uses such a setup though, to me it seems not :-)
I've added the generated dist to a plunker to proof the example still works:
http://embed.plnkr.co/9TNQVwHemhVElcgroXxE/preview
=> Remove window.React from source files

package.json
Fixes an issue where a project that does not already include reactify (e.g. a CoffeeScript project) would throw exceptions during the build because there was no reactify module.
Replaces #58.
=> Since the publish scripts already reactify the source, Browserify needs no further transforms.

README.md, src/tokenizer/index.js
Hey @fmoo,
I added the modified token to the function signature of the token modification callbacks. In my opinion, the modified token should come first, and the selectedTokens should come second, but I didn't want to introduce a non backward compatible change. According to the current readme, it appears as if this is the intended functionality, but not what the code does. Anyway, the order doesn't really matter. What do you think of this PR?
Thanks!
=> return modified token in callback props

README.md, dist/react-typeahead.js, examples/typeahead-custom-options.html, src/typeahead/index.js, src/typeahead/option.js, src/typeahead/selector.js, test/bundle.js, test/typeahead-test.js
I needed to extend the typeahead to be able to provide custom options (arbitrary options rather than strings) together with `getSearchString()` and `getDisplayString` functions.
I made sure to not break downward compatibility, wrote tests, added an example and updated the documentation. Maybe others will also find this feature useful :)
Beware that it includes [this pull request](https://github.com/fmoo/react-typeahead/pull/33) which is not yet merged, since I was branching from it.
=> Custom options

README.md, src/tokenizer/index.js, src/typeahead/index.js, test/tokenizer-test.js, test/typeahead-test.js
added two exposed component functions to focus the input.
Useful when rendering a parent component and you want to immediatly focus this input for the user
I found that `React.findDOMNode(this.tokenizer.refs.typeahead.refs.entry).focus()` was too cumbersome and brittle. I don't know if you'd rather expose the input in a more graceful way or keep the `focus` function as the only supported exposed way to access the input.
=> added Typeahead#focus and Tokenizer#focus

src/typeahead/index.js, src/typeahead/option.js, src/typeahead/selector.js, test/typeahead-test.js
The state is now fully contained in Typeahead, this opens up the possibility of replacing TypeaheadSelector to add functionality to it as the interface between it and Typeahead is simpler.
=> Extract State from inner components

README.md, src/typeahead/index.js, test/typeahead-test.js
Hello,
As I said before, I needed this kind of simple functionality.
I know it is kinda a duplicate with #34, but the aim is much simpler, implications are much smaller, and it would fit 90% of usages for this.
Unit tests are included also, and are all passing.
=> Added ability to change <input> to <textarea> from a boolean flag

src/typeahead/selector.js
Hi!
Today I found a problem in case when collection consists of elements with no unique displayOption. I've been got an exception from React about that.
This small PR will add unique key for each filtered item.
=> Specify Unique key instead of displayString

README.md, src/typeahead/index.js, test/typeahead-test.js
Allow user set input's value explicitly so it's more useful in 'edit' scenario.
More discussion see https://github.com/fmoo/react-typeahead/pull/82
=> add `value` option to set typeahead input's value

README.md, src/typeahead/index.js, test/typeahead-test.js
This allows more customisation of the results and also simplifies the creation of a empty results message inside the customListComponent.
=> Replace TypeaheadSelector with custom Component

README.md
It turns out that the actual prop passed into the custom list component is not `selectedIndex`, but `selectionIndex`
See the default one:
https://github.com/fmoo/react-typeahead/blob/master/src/typeahead/selector.js#L18
=> Change prop name in README from selectedIndex to selectionIndex

src/typeahead/index.js
I would like to allow the user to be able to shift-tab to navigate backwards from a Typeahead input. However, the _onKeyDown handler was capturing it as a "tab". 
Since none of the built in handlers are looking for "shift", I fixed this issue by passing the keyDown event directly up to the handler if the shift key is pressed.
=> Use upstream keydown handler if the user is pressing shift

src/typeahead/index.js
@thehuey, 
Here's a PR that includes a benchmark test. It's run by calling `npm run benchmark`.
This is the output I get:
```
running with 10000 items
original x 38.72 ops/sec ±1.35% (52 runs sampled)
short circuit x 6,076 ops/sec ±1.91% (85 runs sampled)
Fastest is short circuit
```
The effect is dramatic. And it gets much more dramatic the more items in the list.
I don't know if you want to add the option `searchOnBlankValue` or not, but I needed it to run the benchmark.
Addresses #124.
=> Short circuit updating visible when entry is empty

src/typeahead/index.js
This change prevents `visible` from being populated on render after entryText has been cleared.
Fixes #162
=> Fix cWRP to look at new values

README.md, src/typeahead/index.js, test/typeahead-test.js
Previously, options do not show when the value is empty. This PR adds a prop `skipBlankSearch` that allows that behavior to be configurable.
By default, options will still not render when the value is empty.
=> Make skipping blank searches configurable

README.md, src/tokenizer/index.js, src/typeahead/index.js, test/tokenizer-test.js, test/typeahead-test.js
I wanted to add onKeyPress events to a `<Typeahead />` component as is often done in inputs and was surprised to see they weren't triggered. Here's an implementation for them (basically the same that onKeyUp's)
=> feat: add onKeyPress support

src/typeahead/index.js, src/typeahead/selector.js
I originally had the issue of the selector being displayed even when there are no options.
If I am not allowing custom values and type something with no suggestions, the selector is displayed even when the input isn't focused:
I changed it so that the selector component won't display if there are no options available and custom values aren't allowed. I had to send `allowCustomValues` as a prop because it wasn't possible to distinguish whether custom values were allowed or not with the existing `customValue` prop alone. The value of `null` for `customValue` can mean that custom values aren't allowed, the current input has less characters than specified, or the input matches an existing option.
=> Don't render selector if there are no options to display

README.md, src/accessor.js, src/tokenizer/index.js, src/tokenizer/token.js, src/typeahead/index.js, test/tokenizer-test.js
`Typeahead` has the `formInputOption` property, which can be used to transform a complex option to a form input value. It would be nice to have the same thing for `Tokenizer`.
=> Allowing custom tokenizer token values

package.json, src/tokenizer/index.js, src/typeahead/index.js, test/typeahead-test.js
I have identified warnings regarding the new warning added in react 15,
as discussed on react blog and github PR
https://facebook.github.io/react/blog/2016/04/07/react-v15.html#new-deprecations-introduced-with-a-warning
https://github.com/facebook/react/pull/5048
This PR contains how to identify the problem:
new run script:
npm run test:react:15
```
[16:01:26] Starting 'test'...
Warning: Input elements must be either controlled or uncontrolled (specify either the value prop, or the defaultValue prop, but not both). Decide between using a controlled or uncontrolled input element and remove one of these props. More info: https://fb.me/react-controlled-components
․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․Warning: `value` prop on `input` should not be null. Consider using the empty string to clear …
```
=> react 14 and 15 testing identified warning in react 15

README.md, src/typeahead/index.js, src/typeahead/selector.js, test/typeahead-test.js
If more than `maxVisible` results are specified, options matching the `entryValue` are truncated without any message. This can be misleading to a user who does not know about the internals of the dropdown.
If specified, `resultsTruncatedMessage` is displayed at the bottom of the results dropdown when more than `maxVisible` results are returned after filtering.
Example with styling: 
Also includes a new key for `customClasses`, `resultsTruncated`
=> display a message if the results list is truncated

src/typeahead/index.js, test/typeahead-test.js
There is an config option for `showOptionsWhenEmpty`, but the problem is there is no way to hide the options if you use it. What we really want is to show the options when you click into the input (on focus) if there is no input text.
=> Show when showOptionsWhenEmpty is true only if the input is focused

README.md, examples/tokenizer-topcoat.html, src/tokenizer/index.js, src/typeahead/index.js, test/typeahead-test.js
Related to:
https://github.com/fmoo/react-typeahead/issues/42
https://github.com/fmoo/react-typeahead/issues/83
Right now react-typeahead doesn't allow you to provide a way to do complex filtering on the options provided. This PR adds a new prop called `searchOptions` that allows the user to sort, filter, and map the results in any way necessary.
The default fuzzy search gets access to more advanced functionality than `filterOption` provides, the main purpose of this PR is to allow users to access that functionality.
I needed this functionality to provide information to the `displayOption` prop about which characters were being matched in a fuzzy search, but in order to save that information, the best way would be to have some metadata stored with the results. Providing a mapping function …
=> Add more flexible filtering (searchOptions and inputDisplayOptions prop)

README.md
[In the code for this example](http://wookiehangover.github.io/react-typeahead/examples/tokenizer-topcoat.html), I saw that you can pass a custom class for the `token`.
Wanted to ensure this was reflected in the documentation.
Thanks again for maintaining this very useful component!
=> README update: add 'token' to list of customClasses for Tokenizer component

src/typeahead/option.js, test/typeahead-test.js
`onClick` is not fired when clicked on a TypeaheadOption. This adds a `onMouseDown` workaround with the same handler to handle clicks by default.
Adds tests to test `onClick` and `onMouseDown` events, `onClick` test is set as pending until resolved.
Since the whole master branch test suit fails as mentioned in #229, these tests couldn't be verified, but should be fine as soon as the main issue is resolved.
=> Adds onMouseDown workaround to TypeaheadOption

.gitignore, src/typeahead/index.js
fixed problem: list is constantly popping up when Typehead component used with managed `value`, i.e.:
```
class Page extends React.Component{
render(){
return <Typehead 
value={this.state.myValue} 
onBlur={(e)=>this.setState({myValue: e.target.value}) }
options={["AAA","BBB"]}
/>`
}
}
```
=> fixed problem: list is constantly popping up when Typehead component used with managed `value`
